language: cpp
compiler: gcc
dist: bionic
sudo: true


addons:
  apt:
    packages: clang-format colordiff lcov libboost-all-dev

script:
  - bash linter.sh
  - ./build.sh -t
  - ./build.sh -c

after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
