name: C/C++ CI


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: apt
      run: sudo apt-get install g++ cmake lcov libboost-all-dev
    - name: submodule
      run: git submodule update --init --recursive
    - name: test
      run: ./build.sh -t
